### ISSUE TITLE
Git pull and hooks

### ISSUE THREAD

**Issue by dariooddenino** [joelmccracken/reddup#15]
I was thinking yesterday of automating a bit the handling of dotfiles with stow, but then I remembered about reddup!
I think that this could be done with two "simple" changes:
- Add the ability to pull new changes from remote repositories automatically (from the docs it seems like it's not there)
- Add hooks (which could just be simple bash commands)

For example (pseudo syntax):
```
locations:
  - type: git
    location: ~/.dotfiles
    pull: true
    on_pull: 
      - `stow my stuff` 
```
